#cloud-config
users:
  - name: ansible
    groups: ssh-users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDInOYg/UVWMQki7VGZ2QdOzMLOdgpxmociPA+7mnhReaffH5Z/296mxiQ4FD3IIkuoTKGcWaLDvV1K5D3f34LeIMD9tW6EzJKWQ62hH6zhAUgHOaMdkUJSfl2S62A8mRlphxupCXubwZ6IEdAGiL5yWUU3MJ4CpTZEMQNdFAoiGbfluAB9CZbnapmDRKnk3qexsqgslkiphwtcTdNkWh19UiU0RI27vtSyj8dbQIpfC/1Zeqe8rcyg7R2AE6yrBn5BPrPIKdgQC92uh/eqMJHMSCgPHqHV97r7YzOxWUbxIvhcasmzWueW6+t3JvIaaaNm047NIAry7ptVq3GjROyu7J7jRz4mqP5o969nYjVPsQlgA05f67Rk5PyZvlWR+rQWoXh2yWVo+I5KW97Q4s3UqRTFL23PU0xU9x7O7RDpUY+X92mkAeT1XYeQKchuwSLPGVxeKeRDOhKLBjrH7TndkPmiZ86thPGgs6iBz3EQ8A6zIW+Q6MMDzLaesMH1COk= ansible@github-actions
packages:
  - tmux
package_update: true
package_upgrade: true
runcmd:
  - sed -i -e '/^\(#\|\)Port 22/s/^.*$/Port 2222/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowGroups ssh-users' /etc/ssh/sshd_config
  - systemctl restart sshd
