- name: Provision
  hosts: localhost

- tasks:

  - name: Create Ansible ssh_key
    hetzner.hcloud.ssh_key:
      name: ansible@github-actions
      public_key: lookup('ansible.builtin.env', 'SSH_PUBLIC_KEY')

  - name: Create Puppet Master
    hetzner.hcloud.server:
      name: puppet-master
      server_type: cx22
      image: centos-9
      enable_ipv4: false
      ssh_keys:
        - ansible@github-actions
