name: Deploy with Ansible

on: push

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          echo "${{ vars.SSH_PUBLIC_KEY }}" > public_key
          chmod 600 private_key

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv
          pip3 install ansible hcloud

      - name: Run Ansible Playbook
        env:
          HCLOUD_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook playbooks/provision.yml
          #ansible-playbook -i inventory.ini playbooks/main.yml --private_key private_key -u ${{ vars.ANSIBLE_USER }}
