name: Deploy with Ansible

on: push

jobs:
  deploy:
    name: Deploy Ansible Playbook
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          HCLOUD_TOKEN: ${{ secrets.SSH_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: False
          SSH_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
        run: |
          ansible-playbook provision.yml
          #ansible-playbook -i playbooks/provision.yml --private_key private_key -u ${{ vars.ANSIBLE_USER }}
